//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportadoraMVC.ActividadReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActividadDTO", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class ActividadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsignadaAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreadaPorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelacionadaConField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AsignadaA {
            get {
                return this.AsignadaAField;
            }
            set {
                if ((object.ReferenceEquals(this.AsignadaAField, value) != true)) {
                    this.AsignadaAField = value;
                    this.RaisePropertyChanged("AsignadaA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreadaPor {
            get {
                return this.CreadaPorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreadaPorField, value) != true)) {
                    this.CreadaPorField = value;
                    this.RaisePropertyChanged("CreadaPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelacionadaCon {
            get {
                return this.RelacionadaConField;
            }
            set {
                if ((object.ReferenceEquals(this.RelacionadaConField, value) != true)) {
                    this.RelacionadaConField = value;
                    this.RaisePropertyChanged("RelacionadaCon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actividad", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class Actividad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AsignadaAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CreadaPorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ActividadReference.Proceso ProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelacionadaConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ActividadReference.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ActividadReference.Usuario Usuario1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AsignadaA {
            get {
                return this.AsignadaAField;
            }
            set {
                if ((this.AsignadaAField.Equals(value) != true)) {
                    this.AsignadaAField = value;
                    this.RaisePropertyChanged("AsignadaA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CreadaPor {
            get {
                return this.CreadaPorField;
            }
            set {
                if ((this.CreadaPorField.Equals(value) != true)) {
                    this.CreadaPorField = value;
                    this.RaisePropertyChanged("CreadaPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ActividadReference.Proceso Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelacionadaCon {
            get {
                return this.RelacionadaConField;
            }
            set {
                if ((this.RelacionadaConField.Equals(value) != true)) {
                    this.RelacionadaConField = value;
                    this.RaisePropertyChanged("RelacionadaCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ActividadReference.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ActividadReference.Usuario Usuario1 {
            get {
                return this.Usuario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario1Field, value) != true)) {
                    this.Usuario1Field = value;
                    this.RaisePropertyChanged("Usuario1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proceso", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class Proceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ActividadReference.Actividad[] ActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ActividadReference.Actividad[] Actividad {
            get {
                return this.ActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadField, value) != true)) {
                    this.ActividadField = value;
                    this.RaisePropertyChanged("Actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ActividadReference.Actividad[] ActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ActividadReference.Actividad[] Actividad1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ActividadReference.Actividad[] Actividad {
            get {
                return this.ActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadField, value) != true)) {
                    this.ActividadField = value;
                    this.RaisePropertyChanged("Actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ActividadReference.Actividad[] Actividad1 {
            get {
                return this.Actividad1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Actividad1Field, value) != true)) {
                    this.Actividad1Field = value;
                    this.RaisePropertyChanged("Actividad1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActividadReference.IActividadService")]
    public interface IActividadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/ListarActividades", ReplyAction="http://tempuri.org/IActividadService/ListarActividadesResponse")]
        TransportadoraMVC.ActividadReference.ActividadDTO[] ListarActividades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/ListarActividades", ReplyAction="http://tempuri.org/IActividadService/ListarActividadesResponse")]
        System.Threading.Tasks.Task<TransportadoraMVC.ActividadReference.ActividadDTO[]> ListarActividadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/BuscarActividad", ReplyAction="http://tempuri.org/IActividadService/BuscarActividadResponse")]
        TransportadoraMVC.ActividadReference.Actividad BuscarActividad(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/BuscarActividad", ReplyAction="http://tempuri.org/IActividadService/BuscarActividadResponse")]
        System.Threading.Tasks.Task<TransportadoraMVC.ActividadReference.Actividad> BuscarActividadAsync(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/AgregarActividad", ReplyAction="http://tempuri.org/IActividadService/AgregarActividadResponse")]
        void AgregarActividad(TransportadoraMVC.ActividadReference.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/AgregarActividad", ReplyAction="http://tempuri.org/IActividadService/AgregarActividadResponse")]
        System.Threading.Tasks.Task AgregarActividadAsync(TransportadoraMVC.ActividadReference.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/EditarActividad", ReplyAction="http://tempuri.org/IActividadService/EditarActividadResponse")]
        void EditarActividad(long Id, TransportadoraMVC.ActividadReference.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/EditarActividad", ReplyAction="http://tempuri.org/IActividadService/EditarActividadResponse")]
        System.Threading.Tasks.Task EditarActividadAsync(long Id, TransportadoraMVC.ActividadReference.Actividad actividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/Confirmacion", ReplyAction="http://tempuri.org/IActividadService/ConfirmacionResponse")]
        void Confirmacion(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/Confirmacion", ReplyAction="http://tempuri.org/IActividadService/ConfirmacionResponse")]
        System.Threading.Tasks.Task ConfirmacionAsync(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/EliminarActividad", ReplyAction="http://tempuri.org/IActividadService/EliminarActividadResponse")]
        void EliminarActividad(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActividadService/EliminarActividad", ReplyAction="http://tempuri.org/IActividadService/EliminarActividadResponse")]
        System.Threading.Tasks.Task EliminarActividadAsync(long Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActividadServiceChannel : TransportadoraMVC.ActividadReference.IActividadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActividadServiceClient : System.ServiceModel.ClientBase<TransportadoraMVC.ActividadReference.IActividadService>, TransportadoraMVC.ActividadReference.IActividadService {
        
        public ActividadServiceClient() {
        }
        
        public ActividadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActividadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActividadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActividadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TransportadoraMVC.ActividadReference.ActividadDTO[] ListarActividades() {
            return base.Channel.ListarActividades();
        }
        
        public System.Threading.Tasks.Task<TransportadoraMVC.ActividadReference.ActividadDTO[]> ListarActividadesAsync() {
            return base.Channel.ListarActividadesAsync();
        }
        
        public TransportadoraMVC.ActividadReference.Actividad BuscarActividad(long Id) {
            return base.Channel.BuscarActividad(Id);
        }
        
        public System.Threading.Tasks.Task<TransportadoraMVC.ActividadReference.Actividad> BuscarActividadAsync(long Id) {
            return base.Channel.BuscarActividadAsync(Id);
        }
        
        public void AgregarActividad(TransportadoraMVC.ActividadReference.Actividad actividad) {
            base.Channel.AgregarActividad(actividad);
        }
        
        public System.Threading.Tasks.Task AgregarActividadAsync(TransportadoraMVC.ActividadReference.Actividad actividad) {
            return base.Channel.AgregarActividadAsync(actividad);
        }
        
        public void EditarActividad(long Id, TransportadoraMVC.ActividadReference.Actividad actividad) {
            base.Channel.EditarActividad(Id, actividad);
        }
        
        public System.Threading.Tasks.Task EditarActividadAsync(long Id, TransportadoraMVC.ActividadReference.Actividad actividad) {
            return base.Channel.EditarActividadAsync(Id, actividad);
        }
        
        public void Confirmacion(long Id) {
            base.Channel.Confirmacion(Id);
        }
        
        public System.Threading.Tasks.Task ConfirmacionAsync(long Id) {
            return base.Channel.ConfirmacionAsync(Id);
        }
        
        public void EliminarActividad(long Id) {
            base.Channel.EliminarActividad(Id);
        }
        
        public System.Threading.Tasks.Task EliminarActividadAsync(long Id) {
            return base.Channel.EliminarActividadAsync(Id);
        }
    }
}
