//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportadoraMVC.ProcesoReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proceso", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class Proceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ProcesoReference.Actividad[] ActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ProcesoReference.Actividad[] Actividad {
            get {
                return this.ActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadField, value) != true)) {
                    this.ActividadField = value;
                    this.RaisePropertyChanged("Actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actividad", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class Actividad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AsignadaAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CreadaPorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ProcesoReference.Proceso ProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelacionadaConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ProcesoReference.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ProcesoReference.Usuario Usuario1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AsignadaA {
            get {
                return this.AsignadaAField;
            }
            set {
                if ((this.AsignadaAField.Equals(value) != true)) {
                    this.AsignadaAField = value;
                    this.RaisePropertyChanged("AsignadaA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CreadaPor {
            get {
                return this.CreadaPorField;
            }
            set {
                if ((this.CreadaPorField.Equals(value) != true)) {
                    this.CreadaPorField = value;
                    this.RaisePropertyChanged("CreadaPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ProcesoReference.Proceso Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelacionadaCon {
            get {
                return this.RelacionadaConField;
            }
            set {
                if ((this.RelacionadaConField.Equals(value) != true)) {
                    this.RelacionadaConField = value;
                    this.RaisePropertyChanged("RelacionadaCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ProcesoReference.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ProcesoReference.Usuario Usuario1 {
            get {
                return this.Usuario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario1Field, value) != true)) {
                    this.Usuario1Field = value;
                    this.RaisePropertyChanged("Usuario1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/TransportadoraService.Models")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ProcesoReference.Actividad[] ActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ProcesoReference.Actividad[] Actividad1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ProcesoReference.Actividad[] Actividad {
            get {
                return this.ActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadField, value) != true)) {
                    this.ActividadField = value;
                    this.RaisePropertyChanged("Actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ProcesoReference.Actividad[] Actividad1 {
            get {
                return this.Actividad1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Actividad1Field, value) != true)) {
                    this.Actividad1Field = value;
                    this.RaisePropertyChanged("Actividad1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcesoReference.IProcesoService")]
    public interface IProcesoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/ListarProcesos", ReplyAction="http://tempuri.org/IProcesoService/ListarProcesosResponse")]
        TransportadoraMVC.ProcesoReference.Proceso[] ListarProcesos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/ListarProcesos", ReplyAction="http://tempuri.org/IProcesoService/ListarProcesosResponse")]
        System.Threading.Tasks.Task<TransportadoraMVC.ProcesoReference.Proceso[]> ListarProcesosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/BuscarProceso", ReplyAction="http://tempuri.org/IProcesoService/BuscarProcesoResponse")]
        TransportadoraMVC.ProcesoReference.Proceso BuscarProceso(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/BuscarProceso", ReplyAction="http://tempuri.org/IProcesoService/BuscarProcesoResponse")]
        System.Threading.Tasks.Task<TransportadoraMVC.ProcesoReference.Proceso> BuscarProcesoAsync(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/AgregarProceso", ReplyAction="http://tempuri.org/IProcesoService/AgregarProcesoResponse")]
        void AgregarProceso(TransportadoraMVC.ProcesoReference.Proceso proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/AgregarProceso", ReplyAction="http://tempuri.org/IProcesoService/AgregarProcesoResponse")]
        System.Threading.Tasks.Task AgregarProcesoAsync(TransportadoraMVC.ProcesoReference.Proceso proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/EditarProceso", ReplyAction="http://tempuri.org/IProcesoService/EditarProcesoResponse")]
        void EditarProceso(long Id, TransportadoraMVC.ProcesoReference.Proceso proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/EditarProceso", ReplyAction="http://tempuri.org/IProcesoService/EditarProcesoResponse")]
        System.Threading.Tasks.Task EditarProcesoAsync(long Id, TransportadoraMVC.ProcesoReference.Proceso proceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/Confirmacion", ReplyAction="http://tempuri.org/IProcesoService/ConfirmacionResponse")]
        void Confirmacion(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/Confirmacion", ReplyAction="http://tempuri.org/IProcesoService/ConfirmacionResponse")]
        System.Threading.Tasks.Task ConfirmacionAsync(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/EliminarProceso", ReplyAction="http://tempuri.org/IProcesoService/EliminarProcesoResponse")]
        void EliminarProceso(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcesoService/EliminarProceso", ReplyAction="http://tempuri.org/IProcesoService/EliminarProcesoResponse")]
        System.Threading.Tasks.Task EliminarProcesoAsync(long Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcesoServiceChannel : TransportadoraMVC.ProcesoReference.IProcesoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcesoServiceClient : System.ServiceModel.ClientBase<TransportadoraMVC.ProcesoReference.IProcesoService>, TransportadoraMVC.ProcesoReference.IProcesoService {
        
        public ProcesoServiceClient() {
        }
        
        public ProcesoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcesoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TransportadoraMVC.ProcesoReference.Proceso[] ListarProcesos() {
            return base.Channel.ListarProcesos();
        }
        
        public System.Threading.Tasks.Task<TransportadoraMVC.ProcesoReference.Proceso[]> ListarProcesosAsync() {
            return base.Channel.ListarProcesosAsync();
        }
        
        public TransportadoraMVC.ProcesoReference.Proceso BuscarProceso(long Id) {
            return base.Channel.BuscarProceso(Id);
        }
        
        public System.Threading.Tasks.Task<TransportadoraMVC.ProcesoReference.Proceso> BuscarProcesoAsync(long Id) {
            return base.Channel.BuscarProcesoAsync(Id);
        }
        
        public void AgregarProceso(TransportadoraMVC.ProcesoReference.Proceso proceso) {
            base.Channel.AgregarProceso(proceso);
        }
        
        public System.Threading.Tasks.Task AgregarProcesoAsync(TransportadoraMVC.ProcesoReference.Proceso proceso) {
            return base.Channel.AgregarProcesoAsync(proceso);
        }
        
        public void EditarProceso(long Id, TransportadoraMVC.ProcesoReference.Proceso proceso) {
            base.Channel.EditarProceso(Id, proceso);
        }
        
        public System.Threading.Tasks.Task EditarProcesoAsync(long Id, TransportadoraMVC.ProcesoReference.Proceso proceso) {
            return base.Channel.EditarProcesoAsync(Id, proceso);
        }
        
        public void Confirmacion(long Id) {
            base.Channel.Confirmacion(Id);
        }
        
        public System.Threading.Tasks.Task ConfirmacionAsync(long Id) {
            return base.Channel.ConfirmacionAsync(Id);
        }
        
        public void EliminarProceso(long Id) {
            base.Channel.EliminarProceso(Id);
        }
        
        public System.Threading.Tasks.Task EliminarProcesoAsync(long Id) {
            return base.Channel.EliminarProcesoAsync(Id);
        }
    }
}
