//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranspService.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public long Id { get; set; }
        public Nullable<long> CreadaPor { get; set; }
        public Nullable<long> AsignadaA { get; set; }
        public Nullable<long> RelacionadaCon { get; set; }
        public string Asunto { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string Prioridad { get; set; }
    
        public virtual Proceso Proceso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
