//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranspService.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
    }
}
