//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportadoraMVC.ReferenceActividad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actividad", Namespace="http://schemas.datacontract.org/2004/07/TranspService.Modelos")]
    [System.SerializableAttribute()]
    public partial class Actividad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AsignadaAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CreadaPorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ReferenceActividad.Proceso ProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RelacionadaConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ReferenceActividad.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ReferenceActividad.Usuario Usuario1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AsignadaA {
            get {
                return this.AsignadaAField;
            }
            set {
                if ((this.AsignadaAField.Equals(value) != true)) {
                    this.AsignadaAField = value;
                    this.RaisePropertyChanged("AsignadaA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CreadaPor {
            get {
                return this.CreadaPorField;
            }
            set {
                if ((this.CreadaPorField.Equals(value) != true)) {
                    this.CreadaPorField = value;
                    this.RaisePropertyChanged("CreadaPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadField, value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ReferenceActividad.Proceso Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RelacionadaCon {
            get {
                return this.RelacionadaConField;
            }
            set {
                if ((this.RelacionadaConField.Equals(value) != true)) {
                    this.RelacionadaConField = value;
                    this.RaisePropertyChanged("RelacionadaCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ReferenceActividad.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ReferenceActividad.Usuario Usuario1 {
            get {
                return this.Usuario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario1Field, value) != true)) {
                    this.Usuario1Field = value;
                    this.RaisePropertyChanged("Usuario1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proceso", Namespace="http://schemas.datacontract.org/2004/07/TranspService.Modelos")]
    [System.SerializableAttribute()]
    public partial class Proceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ReferenceActividad.Actividad[] ActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ReferenceActividad.Actividad[] Actividad {
            get {
                return this.ActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadField, value) != true)) {
                    this.ActividadField = value;
                    this.RaisePropertyChanged("Actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/TranspService.Modelos")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ReferenceActividad.Actividad[] ActividadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransportadoraMVC.ReferenceActividad.Actividad[] Actividad1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ReferenceActividad.Actividad[] Actividad {
            get {
                return this.ActividadField;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadField, value) != true)) {
                    this.ActividadField = value;
                    this.RaisePropertyChanged("Actividad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TransportadoraMVC.ReferenceActividad.Actividad[] Actividad1 {
            get {
                return this.Actividad1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Actividad1Field, value) != true)) {
                    this.Actividad1Field = value;
                    this.RaisePropertyChanged("Actividad1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceActividad.IServiceActividad")]
    public interface IServiceActividad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/ListarActividad", ReplyAction="http://tempuri.org/IServiceActividad/ListarActividadResponse")]
        TransportadoraMVC.ReferenceActividad.Actividad[] ListarActividad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/ListarActividad", ReplyAction="http://tempuri.org/IServiceActividad/ListarActividadResponse")]
        System.Threading.Tasks.Task<TransportadoraMVC.ReferenceActividad.Actividad[]> ListarActividadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/AgregarActividad", ReplyAction="http://tempuri.org/IServiceActividad/AgregarActividadResponse")]
        void AgregarActividad(TransportadoraMVC.ReferenceActividad.Actividad act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/AgregarActividad", ReplyAction="http://tempuri.org/IServiceActividad/AgregarActividadResponse")]
        System.Threading.Tasks.Task AgregarActividadAsync(TransportadoraMVC.ReferenceActividad.Actividad act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/EditarActividad", ReplyAction="http://tempuri.org/IServiceActividad/EditarActividadResponse")]
        void EditarActividad(long Id, TransportadoraMVC.ReferenceActividad.Actividad act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/EditarActividad", ReplyAction="http://tempuri.org/IServiceActividad/EditarActividadResponse")]
        System.Threading.Tasks.Task EditarActividadAsync(long Id, TransportadoraMVC.ReferenceActividad.Actividad act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/EliminarActividad", ReplyAction="http://tempuri.org/IServiceActividad/EliminarActividadResponse")]
        void EliminarActividad(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/EliminarActividad", ReplyAction="http://tempuri.org/IServiceActividad/EliminarActividadResponse")]
        System.Threading.Tasks.Task EliminarActividadAsync(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/BuscarActividad", ReplyAction="http://tempuri.org/IServiceActividad/BuscarActividadResponse")]
        TransportadoraMVC.ReferenceActividad.Actividad BuscarActividad(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActividad/BuscarActividad", ReplyAction="http://tempuri.org/IServiceActividad/BuscarActividadResponse")]
        System.Threading.Tasks.Task<TransportadoraMVC.ReferenceActividad.Actividad> BuscarActividadAsync(long Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceActividadChannel : TransportadoraMVC.ReferenceActividad.IServiceActividad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceActividadClient : System.ServiceModel.ClientBase<TransportadoraMVC.ReferenceActividad.IServiceActividad>, TransportadoraMVC.ReferenceActividad.IServiceActividad {
        
        public ServiceActividadClient() {
        }
        
        public ServiceActividadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceActividadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceActividadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceActividadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TransportadoraMVC.ReferenceActividad.Actividad[] ListarActividad() {
            return base.Channel.ListarActividad();
        }
        
        public System.Threading.Tasks.Task<TransportadoraMVC.ReferenceActividad.Actividad[]> ListarActividadAsync() {
            return base.Channel.ListarActividadAsync();
        }
        
        public void AgregarActividad(TransportadoraMVC.ReferenceActividad.Actividad act) {
            base.Channel.AgregarActividad(act);
        }
        
        public System.Threading.Tasks.Task AgregarActividadAsync(TransportadoraMVC.ReferenceActividad.Actividad act) {
            return base.Channel.AgregarActividadAsync(act);
        }
        
        public void EditarActividad(long Id, TransportadoraMVC.ReferenceActividad.Actividad act) {
            base.Channel.EditarActividad(Id, act);
        }
        
        public System.Threading.Tasks.Task EditarActividadAsync(long Id, TransportadoraMVC.ReferenceActividad.Actividad act) {
            return base.Channel.EditarActividadAsync(Id, act);
        }
        
        public void EliminarActividad(long Id) {
            base.Channel.EliminarActividad(Id);
        }
        
        public System.Threading.Tasks.Task EliminarActividadAsync(long Id) {
            return base.Channel.EliminarActividadAsync(Id);
        }
        
        public TransportadoraMVC.ReferenceActividad.Actividad BuscarActividad(long Id) {
            return base.Channel.BuscarActividad(Id);
        }
        
        public System.Threading.Tasks.Task<TransportadoraMVC.ReferenceActividad.Actividad> BuscarActividadAsync(long Id) {
            return base.Channel.BuscarActividadAsync(Id);
        }
    }
}
