//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportadoraService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportadoraEntities : DbContext
    {
        public TransportadoraEntities()
            : base("name=TransportadoraEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Embarque> Embarque { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Proceso> Proceso { get; set; }
        public virtual DbSet<Trazabilidad> Trazabilidad { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
