//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportadoraMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embarque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Embarque()
        {
            this.Trazabilidad = new HashSet<Trazabilidad>();
        }
    
        public long Id { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Contacto { get; set; }
        public string OrdenCompra { get; set; }
        public string Consignatario { get; set; }
        public string ZonaAduanera { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string EmbarqueAereo { get; set; }
        public string EmbarqueMaritimo { get; set; }
        public string Contenedor { get; set; }
        public string INCOTERM { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trazabilidad> Trazabilidad { get; set; }
    }
}
