//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportadoraMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trazabilidad
    {
        public long Id { get; set; }
        public string TipoOperacion { get; set; }
        public string PaisOrigen { get; set; }
        public string CiudadOrigen { get; set; }
        public string PaisDestino { get; set; }
        public string CiudadDesstino { get; set; }
        public Nullable<decimal> Kilos { get; set; }
        public Nullable<decimal> Teus { get; set; }
        public Nullable<long> IdEmbarque { get; set; }
    
        public virtual Embarque Embarque { get; set; }
    }
}
